//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int PDID { get; set; }
        public string ProductID { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string Storage { get; set; }
        public string GraphicsCard { get; set; }
        public string Screen { get; set; }
        public string KeyBoard { get; set; }
        public string Audio { get; set; }
        public string LAN { get; set; }
        public string Wireless { get; set; }
        public string Webcam { get; set; }
        public string CommPort { get; set; }
        public string OperatingSystem { get; set; }
        public string Batery { get; set; }
        public string Weight { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
